q1: Create a 1D array of numbers from 0 to 9

In [1]:
import numpy as np
arr1=np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


q2: Create a 3×3 numpy array of all True’s

In [3]:
arr1=np.array([[True,True,True],[True,True,True],[True,True,True]])
print(arr1)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


q3: Extract all odd numbers from an array of n numbers

In [7]:
n=int(input("Enter the value of n:"))
list1=[i for i in range(n+1)]
arr1=np.array(list1)
for i in arr1:
    if i%2!=0:
        arr1=np.delete(arr1,np.where(arr1==i))
print(arr1)

Enter the value of n:13
[ 0  2  4  6  8 10 12]


q4: Replace all odd numbers in array with -1

In [10]:
n=int(input("Enter the value of n:"))
list1=[i for i in range(n+1)]
arr1=np.array(list1)
for i in arr1:
    if i%2!=0:
        arr1[arr1==i]=-1
print(arr1)

Enter the value of n:13
[ 0 -1  2 -1  4 -1  6 -1  8 -1 10 -1 12 -1]


q5: Convert a 1D array to a 2D array with 2 rows


In [13]:
arr = np.array([1, 6, 3, 9, 5, 10, 11, 8])
arr2 = arr.reshape(2, 4)
print ('After reshaping and having 2 rows:')
print (arr2)

After reshaping and having 2 rows:
[[ 1  6  3  9]
 [ 5 10 11  8]]


q6: Get the common items between two arrays

In [16]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([4,5,6,7,8,9,10])
result = np.intersect1d(arr1, arr2)
print("The common elements are:", result)

The common elements are: [4 5 6]


q7: From array - a remove all items present in array - b

In [17]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([4,5,6,7,8,9,10])
result=np.setdiff1d(arr1, arr2, assume_unique=True)#arr1 and arr2 are unique
print(result)

[1 2 3]


Download the Iris Data CSV File from link - https://drive.google.com/file/d/1KzIR0hK9F17jhzOT3KH2mmWrCoDWpDpQ/view?usp=sharing



q8: Find the mean, median, standard deviation of iris's sepallength (1st column)

In [28]:
import pandas as pd
import math 
df=pd.read_csv('Iris.csv')
b=df.iloc[:,1].values#to get value of the column sepallength
length=len(b)
mean= np.mean(b)
print("Mean is:",round(mean,2))#to roundoff til 2 decimal places
median=np.median(b)
print("Median is:",round(median,2))
sum=0
for i in b:
    sum=sum+((i-mean)**2)
sd=math.sqrt(sum/(length-1))
print("Standard deviation is:",sd)    

Mean is: 5.84
Median is: 5.8
Standard deviation is: 0.8280661279778628


q9: Create a normalized form of iris's sepallength whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.

Use following Normalization Formula ->

 x normalized = (x – x minimum) / (x maximum – x minimum)

In [45]:
b=df.iloc[:,1].values
list1=[]
for i in b:
    x=(i-np.min(b))/(np.max(b)-np.min(b))
    list1.append(x)
print("Normalised sepallength is:\n",list1)

Normalised sepallength is:
 [0.22222222222222213, 0.1666666666666668, 0.11111111111111119, 0.08333333333333327, 0.19444444444444448, 0.30555555555555564, 0.08333333333333327, 0.19444444444444448, 0.027777777777777922, 0.1666666666666668, 0.30555555555555564, 0.13888888888888887, 0.13888888888888887, 0.0, 0.41666666666666663, 0.38888888888888895, 0.30555555555555564, 0.22222222222222213, 0.38888888888888895, 0.22222222222222213, 0.30555555555555564, 0.22222222222222213, 0.08333333333333327, 0.22222222222222213, 0.13888888888888887, 0.19444444444444448, 0.19444444444444448, 0.25000000000000006, 0.25000000000000006, 0.11111111111111119, 0.13888888888888887, 0.30555555555555564, 0.25000000000000006, 0.3333333333333333, 0.1666666666666668, 0.19444444444444448, 0.3333333333333333, 0.1666666666666668, 0.027777777777777922, 0.22222222222222213, 0.19444444444444448, 0.055555555555555594, 0.027777777777777922, 0.19444444444444448, 0.22222222222222213, 0.13888888888888887, 0.22222222222222213, 0.

q10: Filter the rows of iris data that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

In [36]:
df=pd.read_csv('Iris.csv')
b=df.loc[(df['PetalLengthCm']>1.5) & (df['SepalLengthCm']<5.0)]
print("Final result is:\n",b)

Final result is:
       Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
11    12            4.8           3.4            1.6           0.2   
24    25            4.8           3.4            1.9           0.2   
29    30            4.7           3.2            1.6           0.2   
30    31            4.8           3.1            1.6           0.2   
57    58            4.9           2.4            3.3           1.0   
106  107            4.9           2.5            4.5           1.7   

             Species  
11       Iris-setosa  
24       Iris-setosa  
29       Iris-setosa  
30       Iris-setosa  
57   Iris-versicolor  
106   Iris-virginica  


q12: Bin the petal length (3rd) column of iris data to form a text array, such that if petal length is:

Less than 3 --> 'small'

3-5 --> 'medium'

->5 --> 'large'


In [48]:
small = []
medium = []
large = []
Petal_length = np.array(df.loc[:,"PetalLengthCm"])
for i in Petal_length:
    if i<3:
        small.append(i)
    elif i>=3 and i<5:
        medium.append(i)
    elif i>5:
        large.append(i)
    else:
        pass
print("Small:",small)
print("Medium:",medium)
print("Large:",large)

Small: [1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.6, 1.4, 1.1, 1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1.0, 1.7, 1.9, 1.6, 1.6, 1.5, 1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2, 1.3, 1.5, 1.3, 1.5, 1.3, 1.3, 1.3, 1.6, 1.9, 1.4, 1.6, 1.4, 1.5, 1.4]
Medium: [4.7, 4.5, 4.9, 4.0, 4.6, 4.5, 4.7, 3.3, 4.6, 3.9, 3.5, 4.2, 4.0, 4.7, 3.6, 4.4, 4.5, 4.1, 4.5, 3.9, 4.8, 4.0, 4.9, 4.7, 4.3, 4.4, 4.8, 4.5, 3.5, 3.8, 3.7, 3.9, 4.5, 4.5, 4.7, 4.4, 4.1, 4.0, 4.4, 4.6, 4.0, 3.3, 4.2, 4.2, 4.2, 4.3, 3.0, 4.1, 4.5, 4.9, 4.9, 4.8, 4.9, 4.8]
Large: [5.1, 6.0, 5.1, 5.9, 5.6, 5.8, 6.6, 6.3, 5.8, 6.1, 5.1, 5.3, 5.5, 5.1, 5.3, 5.5, 6.7, 6.9, 5.7, 6.7, 5.7, 6.0, 5.6, 5.8, 6.1, 6.4, 5.6, 5.1, 5.6, 6.1, 5.6, 5.5, 5.4, 5.6, 5.1, 5.1, 5.9, 5.7, 5.2, 5.2, 5.4, 5.1]


q13: Sort the iris dataset based on sepallength column.

In [39]:
b=df.sort_values('SepalLengthCm')
print("Sorted dataframe based on sapellength is:\n",b)

Sorted dataframe based on sapellength is:
       Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
13    14            4.3           3.0            1.1           0.1   
42    43            4.4           3.2            1.3           0.2   
38    39            4.4           3.0            1.3           0.2   
8      9            4.4           2.9            1.4           0.2   
41    42            4.5           2.3            1.3           0.3   
..   ...            ...           ...            ...           ...   
122  123            7.7           2.8            6.7           2.0   
118  119            7.7           2.6            6.9           2.3   
117  118            7.7           3.8            6.7           2.2   
135  136            7.7           3.0            6.1           2.3   
131  132            7.9           3.8            6.4           2.0   

            Species  
13      Iris-setosa  
42      Iris-setosa  
38      Iris-setosa  
8       Iris-setosa  
41    

q14: Find the most frequent value of petal length (3rd column) in iris dataset.

In [42]:
print("The most frequent value of PetalLengthCm is:",df['PetalLengthCm'].mode()[0])

The most frequent value of PetalLengthCm is: 1.5
